# Workout - Calories Burned Prediction

## 1. Data Loading

In [22]:
import pandas as pd
import numpy as np

In [23]:
url = "https://raw.githubusercontent.com/miloszgroch/Workout---Calories-Burned-Prediction/main/data/Final_data.csv"
df = pd.read_csv(url)

## 2. EDA

In [24]:
pd.set_option('display.max_info_columns', 100)

df.info(verbose=True, max_cols=1000)
#df.head()

pd.DataFrame({
    "dtype": df.dtypes,
    "nulls": df.isna().sum(),
    "unique": df.nunique()
})

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 54 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             20000 non-null  float64
 1   Gender                          20000 non-null  object
 2   Weight (kg)                     20000 non-null  float64
 3   Height (m)                      20000 non-null  float64
 4   Max_BPM                         20000 non-null  float64
 5   Avg_BPM                         20000 non-null  float64
 6   Resting_BPM                     20000 non-null  float64
 7   Session_Duration (hours)        20000 non-null  float64
 8   Calories_Burned                 20000 non-null  float64
 9   Workout_Type                    20000 non-null  object
 10  Fat_Percentage                  20000 non-null  float64
 11  Water_Intake (liters)           20000 non-null  float64
 12  Workout_Frequency (days/week)   20000 non-null  float64
 13  Experience_Level                20000 non-null  float64
 14  BMI                             20000 non-null  float64
 15  Daily meals frequency           20000 non-null  float64
 16  Physical exercise               20000 non-null  float64
 17  Carbs                           20000 non-null  float64
 18  Proteins                        20000 non-null  float64
 19  Fats                            20000 non-null  float64
 20  Calories                        20000 non-null  float64
 21  meal_name                       20000 non-null  object
 22  meal_type                       20000 non-null  object
 23  diet_type                       20000 non-null  object
 24  sugar_g                         20000 non-null  float64
 25  sodium_mg                       20000 non-null  float64
 26  cholesterol_mg                  20000 non-null  float64
 27  serving_size_g                  20000 non-null  float64
 28  cooking_method                  20000 non-null  object
 29  prep_time_min                   20000 non-null  float64
 30  cook_time_min                   20000 non-null  float64
 31  rating                          20000 non-null  float64
 32  Name of Exercise                20000 non-null  object
 33  Sets                            20000 non-null  float64
 34  Reps                            20000 non-null  float64
 35  Benefit                         20000 non-null  object
 36  Burns Calories (per 30 min)     20000 non-null  float64
 37  Target Muscle Group             20000 non-null  object
 38  Equipment Needed                20000 non-null  object
 39  Difficulty Level                20000 non-null  object
 40  Body Part                       20000 non-null  object
 41  Type of Muscle                  20000 non-null  object
 42  Workout                         20000 non-null  object
 43  BMI_calc                        20000 non-null  float64
 44  cal_from_macros                 20000 non-null  float64
 45  pct_carbs                       20000 non-null  float64
 46  protein_per_kg                  20000 non-null  float64
 47  pct_HRR                         20000 non-null  float64
 48  pct_maxHR                       20000 non-null  float64
 49  cal_balance                     20000 non-null  float64
 50  lean_mass_kg                    20000 non-null  float64
 51  expected_burn                   20000 non-null  float64
 52  Burns Calories (per 30 min)_bc  20000 non-null  float64
 53  Burns_Calories_Bin              20000 non-null  object
dtypes: float64(39), object(15)
memory usage: 8.2+ MB

                                  dtype  nulls  unique
Age                             float64      0    3950
Gender                           object      0       2
Weight (kg)                     float64      0    7042
Height (m)                      float64      0      53
Max_BPM                         float64      0    3808
Avg_BPM                         float64      0    4801
Resting_BPM                     float64      0    1939
Session_Duration (hours)        float64      0     154
Calories_Burned                 float64      0    4587
Workout_Type                     object      0       4
Fat_Percentage                  float64      0   18492
Water_Intake (liters)           float64      0     198
Workout_Frequency (days/week)   float64      0      55
Experience_Level                float64      0      32
BMI                             float64      0    3059
Daily meals frequency           float64      0      31
Physical exercise               float64      0      67
Carbs                           float64      0   12089
Proteins                        float64      0    7332
Fats                            float64      0    5524
Calories                        float64      0    2471
meal_name                        object      0       1
meal_type                        object      0       4
diet_type                        object      0       6
sugar_g                         float64      0    4947
sodium_mg                       float64      0   19152
cholesterol_mg                  float64      0   14545
serving_size_g                  float64      0   15581
cooking_method                   object      0       7
prep_time_min                   float64      0    5384
cook_time_min                   float64      0    9406
rating                          float64      0     414
Name of Exercise                 object      0      55
Sets                            float64      0      30
Reps                            float64      0     654
Benefit                          object      0      49
Burns Calories (per 30 min)     float64      0    5766
Target Muscle Group              object      0      36
Equipment Needed                 object      0      20
Difficulty Level                 object      0       3
Body Part                        object      0       7
Type of Muscle                   object      0      13
Workout                          object      0      53
BMI_calc                        float64      0   18155
cal_from_macros                 float64      0   18808
pct_carbs                       float64      0   19982
protein_per_kg                  float64      0   19986
pct_HRR                         float64      0   19988
pct_maxHR                       float64      0   19965
cal_balance                     float64      0   18736
lean_mass_kg                    float64      0   19693
expected_burn                   float64      0   19296
Burns Calories (per 30 min)_bc  float64      0    5766
Burns_Calories_Bin               object      0       4

In [25]:
df.describe()

,Age,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Fat_Percentage,Water_Intake (liters),...,BMI_calc,cal_from_macros,pct_carbs,protein_per_kg,pct_HRR,pct_maxHR,cal_balance,lean_mass_kg,expected_burn,Burns Calories (per 30 min)_bc
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,2.000000e+04
mean,38.851453,73.898832,1.723093,179.889702,143.704306,62.195813,1.259446,1280.109600,26.101313,2.627485,...,24.921651,1998.297076,0.499983,1.460142,0.699005,0.802305,744.308699,53.786384,866.352318,8.631802e+19
std,12.114580,21.173010,0.127033,11.510805,14.267688,7.289351,0.341336,502.228982,4.996160,0.604724,...,6.701144,440.848408,0.001455,0.518946,0.144880,0.096613,720.946619,12.498740,250.317069,3.197579e+19
min,18.000000,39.180000,1.490000,159.310000,119.070000,49.490000,0.490000,323.110000,11.333134,1.460000,...,12.037907,1105.570000,0.492434,0.516706,0.371344,0.599789,-1266.220000,30.946261,219.852800,2.491905e+16
25%,28.170000,58.160000,1.620000,170.057500,131.220000,55.960000,1.050000,910.800000,22.387807,2.170000,...,20.094975,1661.022500,0.499054,1.076294,0.583656,0.727676,261.432500,44.587037,714.098250,6.441978e+19
50%,39.865000,70.000000,1.710000,180.140000,142.990000,62.200000,1.270000,1231.450000,25.822504,2.610000,...,24.119097,1943.130000,0.499981,1.382260,0.686284,0.794834,691.190000,51.204908,868.721400,8.371578e+19
75%,49.630000,86.100000,1.800000,189.425000,156.060000,68.090000,1.460000,1553.112500,29.676026,3.120000,...,28.562620,2271.950000,0.500910,1.750495,0.798196,0.869211,1176.290000,61.939016,1012.532700,1.100442e+20
max,59.670000,130.770000,2.010000,199.640000,169.840000,74.500000,2.020000,2890.820000,35.000000,3.730000,...,50.229544,3699.540000,0.507889,3.916881,1.073939,1.047032,3075.580000,90.117371,1477.108800,1.756614e+20

### Investigate target column (workout type)

In [26]:
df['Workout_Type'].value_counts()

Workout_Type
Strength    5071
Yoga        5032
HIIT        4974
Cardio      4923
Name: count, dtype: int64